### ISSUE TITLE
Issue with compiling code.  error[E0310] for rustc-serialize-0.3.23 

### ISSUE THREAD

**Issue by reneeisnowhere** [guertinlab/Tn5bias#3]
Hello, I am a very new to rust person and  I have been trying to compile seqOutBias to follow along with the vignette for ATAC-seq bias correction.  I cannot get the build to work with my computer.  I pasted the errors below.  Is this something you can help me with?

....
 Compiling num-traits v0.1.37
error[E0310]: the parameter type `T` may not live long enough
    --> /home/reneem/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustc-serialize-0.3.23/src/serialize.rs:1155:5
     |
1155 |     fn decode<D: Decoder>(d: &mut D) -> Result<Cow<'static, T>, D::Error> {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |     |
     |     the parameter type `T` must be valid for the static lifetime...
     |     ...so that the type `T` will meet its required lifetime bounds...
     |
note: ...that is required by this bound
    --> /tmp/rust-20240717-30535-cax4sv/rustc-1.79.0-src/library/alloc/src/borrow.rs:180:30
help: consider adding an explicit lifetime bound
     |
1151 | impl<'a, T: ?Sized + 'static> Decodable for Cow<'a, T>
     |                    +++++++++

   Compiling strsim v0.5.2
   Compiling rust-htslib v0.12.1
   Compiling flate2 v0.2.18
   Compiling tempfile v2.2.0
For more information about this error, try `rustc --explain E0310`.
error: could not compile `rustc-serialize` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

Best,

reneeisnowhere

**Comment by guertinlab** [comment]
This is an issue installing `rust`, but I cannot troubleshoot without the architecture of your computer. I would recommend reaching out to `rust` support
